version: '3.8'

services:
  nuxt:
    build:
      context: .
    image: nuxt_dev
    container_name: nuxt_dev
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "30000:3000"